# Generated by Django 5.0.9 on 2024-11-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("provider", "Loan Provider"),
                    ("customer", "Loan Customer"),
                    ("bank_personnel", "Bank Personnel"),
                ],
                default="provider",
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
