services:
  docs:
    image: bank_loans_local_docs
    container_name: bank_loans_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./bank_loans:/app/bank_loans:z
    ports:
      - '9000:9000'
    command: /start-docs
