# Generated by Django 5.0.9 on 2024-11-19 01:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0002_alter_loanrequest_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankbudget",
            name="budget",
        ),
    ]
