#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
python /app/manage.py migrate --noinput
python /app/manage.py createcachetable
SUPERUSER_EXISTS=$(echo "from django.contrib.auth import get_user_model;User=get_user_model();print(User.objects.filter(username=\"${DJANGO_DEFAULT_SUPERUSER_USERNAME:-admin}\").count())" | python manage.py shell)
test $SUPERUSER_EXISTS == 0 && DJANGO_SUPERUSER_PASSWORD=${DJANGO_DEFAULT_SUPERUSER_PASSWORD:-admin} python manage.py createsuperuser --username ${DJANGO_DEFAULT_SUPERUSER_USERNAME:-admin} --email ${DJANGO_DEFAULT_SUPERUSER_USERNAME:-admin}@bank.com --noinput || true
exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
